### ISSUE TITLE
Implement event system for subscriber

### ISSUE THREAD

**Issue by awishformore** [veltor/veltor-go#15]
Our subscriber might be interested to know when certain events happen, like when we successfully establish a connection to a new peer, or when we disconnect a peer. We can implement this by using event types that we submit on the same channel; that way, they can even include some meta information. Maybe we can generalize the current packet class to something else to combine this.

**Comment by jasonv75** [comment]
Done in da164863241c1593d060b690dd374895c8592191. Added disconnect/connect events for now.
